server:
  port: 8080

spring:
  application:
    name: Demo-Mongo
  data:
    mongodb:
      uri: mongodb+srv://isaelfatamadev:sistemasVG_general@sistemasvg.snqck.mongodb.net/?retryWrites=true&w=majority
      database: EjemploDB

